---
elasticsearch.host: http://elasticsearch:9200

app_search.listen_host: 0.0.0.0

app_search.auth.source: standard
elasticsearch.username: elastic
elasticsearch.password: changeme

For a complete list of settings, please refer to https://swiftype.com/documentation/app-search/self-managed/configuration
