version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Start date
          command: date
      - run:
          name: Check versions
          command: |
            docker version 
            docker-compose --version
            docker --version
            docker-compose --version
      - run:
          name: Starting container
          command: |
            set -x
            docker-compose up -d --build
            sleep 3m
            curl --retry 10 --retry-delay 5 -v http://localhost:9200/
            curl --retry 10 --retry-delay 5 -v http://localhost:5601/
      - run:
          name: End date
          command: date
#https://circleci.com/docs/2.0/docker-compose/
#https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
