version: 2
jobs:
  build:
    machine: true
    working_directory: /app
    steps:
      - checkout
      - run:
          name: Start date
          command: date
      - run:
          name: Starting container
          command: |
            set -x
            docker-compose up -d
      - run:
          name: End date
          command: date
#https://circleci.com/docs/2.0/docker-compose/
#https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
